version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    network_mode: host
    command: php artisan migrate --force && php artisan optimize && php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - .:/var/www/html